vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /pictures/users
            upload_destination: '%kernel.project_dir%/public/pictures/users'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
