vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: pictures/users-profil
            upload_destination: '%kernel.project_dir%/public/pictures/users-profil'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        team_image:
            uri_prefix: pictures/team_image
            upload_destination: '%kernel.project_dir%/public/pictures/team_image'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        article_image:
            uri_prefix: pictures/article-image
            upload_destination: '%kernel.project_dir%/public/pictures/article-image'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
