vich_uploader:
    db_driver: orm

    mappings:
        user_upload:
            uri_prefix: pictures/avatar
            upload_destination: '%kernel.project_dir%/public/pictures/avatar'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        equipe_upload:
            uri_prefix: pictures/equipe
            upload_destination: '%kernel.project_dir%/public/pictures/equipe'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        article_upload:
            uri_prefix: pictures/article
            upload_destination: '%kernel.project_dir%/public/pictures/article'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
